### ISSUE TITLE
where is the code for part of Computational Budget ? 

### ISSUE THREAD

**Issue by chenslcool** [AvivSham/pFedHN#2]
In  your paper 5.2 and table 2, clients with different hardware capacity can use different model architectures.
I wonder how you implement it using pFedHN.
Nice job, thanks!

**Comment by AvivNavon** [comment]
Hi, the hypernetworks (HN) outputs a vector of all target model parameters. Then, according to the client's model capacity, we use only the relevant subset of parameters. Concretely, say we have three target models of sizes `x1, x2, x3`. The HN outputs a vector `V` of size `x1+x2+x3`. Now, if the current client has a model of size `x2`, we use only the `x2` parameters `V[x2:x3]`.
We plan on releasing the corresponding code that implements the models in the future.

**Comment by chenslcool** [comment]
ok, I got it. Thanks.



---Original---
From: "Aviv ***@***.***&gt;
Date: Thu, Jul 1, 2021 21:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AvivSham/pFedHN] where is the code for part of Computational Budget ?  (#2)




 
Hi, the hypernetworks (HN) outputs a vector of all target model parameters. Then, according to the client's model capacity, we use only the relevant subset of parameters. Concretely, say we have three target models of sizes x1, x2, x3. The HN outputs a vector V of size x1+x2+x3. Now, if the current client has a model of size x2, we use only the x2 parameters V[x2:x3].
 We plan on releasing the corresponding code that implements the models in the future.
