### ISSUE TITLE
Algorithm question

### ISSUE THREAD

**Issue by ThinhOn** [AvivSham/pFedHN#3]
Thank you for sharing the source code, it is extremely useful and straightforward. This paper will be one of the main references for my future work. 

I have one question regarding the algorithm: is there any specific reason for choosing only one user per iteration? I guess one reason is to reduce the computational cost, I would appreciate if you could share your thoughts on my question.

Thank you very much for your time. Please stay safe during this time!

**Comment by AvivNavon** [comment]
Hi, there's no specific reason for using a single client at each communication step. The number of clients for communication at each round can be viewed as a hyperparameter (HP) for the pFedHN algorithm. However, we did not experiment with other values for this HP besides 1, so we can not provide further insights into its effect on the optimization process and final model performance.

**Comment by ThinhOn** [comment]
Thank you for your response!
