### ISSUE TITLE
how to update v_i

### ISSUE THREAD

**Issue by PhungLai728** [AvivSham/pFedHN#5]
Dear authors,

It is unclear to me where in your code, you update v_i as in line 11 of Algorithm 1 in your paper (Personalized Federated Learning using Hypernetworks). 

In your code (main/experiments/pfedhn/trainer.py), you compute hnet_grads (line 172 in trainer.py), which is \delta_phi \theta^T \delta \theta, used to update \phi in line 10 of Alg 1. Then you assign values of hnet_grads to update hnet weights (line 177 in trainer.py), which include v_i update. In this case, it seems to me that, you update v_i as follows:

v_i = v_i - alpha \delta_phi \theta^T \delta \theta.

I do not see how you have the components of \delta_vi \phi^T as in line 11 of Alg 1 in the paper.

Could you please explain the v_i update?

Thanks a lot!

**Comment by AvivNavon** [comment]
Hey, 
Please note that v_i is part of `hnet.parameters()`, so the update is consistent (mathematically) with the one specified in Alg. 1 of the paper.

**Comment by PhungLai728** [comment]
Thanks for your prompt response.

Yes, I understood that v_i is part of hnet.parameters(). 

What does hnet_grads (line 172 in the code) imply for?
- Whether it is \delta_phi \theta^T \delta \theta for updating \phi? 
- And it is  \delta_vi \phi^T \delta_phi \theta^T \delta \theta for updating v_i? 

I am still confused about where the term  \delta_vi \phi^T goes in the code if the aforementioned is not the case. Since you have all in the hnet_grads, and use it to update both \phi and v_i.

Thanks,

**Comment by PhungLai728** [comment]
And one more question, in models.py, lines 54 and 55, 
      emd = self.embeddings(idx)
      features = self.mlp(emd)
"features" and "emb", which one is v_i ?

**Comment by AvivNavon** [comment]
`hnet_grads` contains the gradients for all the parameters of the HN (`v` and `phi`). The embeddings `v` are just another layer in the HN, so there's really no difference between `v` and `phi`.

For your second question, `v` is the embedding weights `self.embeddings.weight`. `emb` from `emd = self.embeddings(idx)` is the equivalent of `v_i` from the paper.

**Comment by PhungLai728** [comment]
It is clear to me. Thanks a lot for your answers! I closed the issue.

**Comment by Aaron2Woo** [comment]
@AvivNavon You mentioned that "hnet_grads contains the gradients for all the parameters of the HN (v and phi). The embeddings v are just another layer in the HN, so there's really no difference between v and phi." 

So, it means that \delta_vi \phi^T = 1 ?
