### ISSUE TITLE
v-i update

### ISSUE THREAD

**Issue by PhungLai728** [AvivSham/pFedHN#6]
Dear authors, 

When I look closer to Alg 1 and the code, I concern about updating v_i.

As I tested, if I use num_nodes =50, then the emb size is [50,13] and if I use  num_nodes =75, then the emb size is [75,19]. It means that if at each iteration, you use one client to update the model, so only one row of the emb will be updated. I also checked the gradient, it is correct with what I understand (only 1 row of the grad has values not 0, and all other rows are 0). 

However, in the optimizer, you use SGD with momentum=0.9. In that case, it does update other rows of the emb, not only at the selected client. This is different from the update rule that you have in Alg 1. If I use SGD without momentum, it only updates 1 row as expected (as the same as Alg 1). 

Do you have any reason or insights in this case? Why you use 1 client, but update all embedding of all clients in your experiments, which is different from Alg.1?

**Comment by AvivNavon** [comment]
That's a good point. If it's an issue for you, you can easily modify the code to apply momentum updates to all parameters excluding the embedding matrix.

**Comment by PhungLai728** [comment]
Sure, thanks for your confirmation!
