### ISSUE TITLE
About some parameters?

### ISSUE THREAD

**Issue by aaa1999** [AvivSham/pFedHN#7]
Please,I read the sources some times.But,How is an epoch counted? The eval_every parameter is the epoch?I am the new to pFedHN.Please,thank you.

**Comment by AvivNavon** [comment]
Hi, we do not use the notation of epochs in our learning setups. Instead, we train pFedHN over 5000 server-client communication steps. Please note that for pFedHN we also have local optimization steps on the client-side (which are naturally not counted as part of the server-client communication steps).

**Comment by aaa1999** [comment]
I think that the eval_every is the alike the epoch parameter.Is that really right?

**Comment by AvivNavon** [comment]
No. Generally, an epoch refers to one pass over the entire training data. The eval_every param sets the evaluation frequency in terms of optimization steps over the hypernetwork.

**Comment by aaa1999** [comment]
oh,well,that's fine.Thank you a lot.
