### ISSUE TITLE
Generalization to Novel Clients

### ISSUE THREAD

**Issue by haolanut** [AvivSham/pFedHN#8]
Hi,

In Section 5.3, you mentioned the generalization to novel clients. However, I didn't find the implementation of generalization in this git repo. Could you please provide the code or details for reproducing the result in Figure 2?

Thanks!

**Comment by AvivSham** [comment]
Hi @haolanut,
How are you?
Currently, we do not have plans to release the generalization experiment. The first paragraph in Sec. 5.3 describes in detail how to train the hypernetwork using the novel clients and the second how to split the data.
If you have specific questions regarding this experiment please write them down and we will be happy to help you to clarify them and reproduce the results.
